### ISSUE TITLE
How about this?

### ISSUE THREAD

**Issue by egasimus** [kriskowal/q-connection#38]
Just off the top of my head, if we have this object exposed over q-connection:

`{ foo: { bar: 1, baz: [2, 3, 4] } }`

why can't we have this syntax to get both `foo.bar` and `foo.baz[1]`?

```
client
  .get(["foo", "bar"], ["foo", "baz", 1])
  .spread(function (a, b) {
    assert a === 1;
    assert b === 3;
  });
```

Probably could work just as well for calling multiple functions at the same time, etc.

**Comment by kriskowal** [comment]
`get` is and will always be atomic, representing async `.`. As such, this should work:

```js
Q(
    client.get('foo').get('bar'),
    client.get('foo').get('baz').get(1)
).spread(function (a, b) {
})
```

And of course @erights hopes that this eventually gets syntax to make it less verbose. Would probably look like:

```
let foo = client!foo;
Promise.all([foo!bar, foo!baz!1])
.then(([a, b]) => {
})
```

**Comment by egasimus** [comment]
Ugh, exclamation marks? How would one procedurally generate such an identifier with that syntax I wonder. Or access a string key.

**Comment by kriskowal** [comment]
@egasimus By analogy…

`a!b` is `a.get('b')`

`a!b(...)` is `a.invoke('b', ...)`

`a!['b']` is `a.get('b')`

Proxy went a different way for `invoke`, composing `get` and `call`. No idea how that would compose for promises at this early stage.

**Comment by erights** [comment]
On Aug 3, 2015 11:06 AM, "Kris Kowal" <notifications@github.com> wrote:
>
> @egasimus By analogy…
>
> a!b is a.get('b')

Q(a).get('b')

> a!b(...) is a.invoke('b', ...)

Q(a).invoke('b', ...)

> a!['b'] is a.get('b')

Q(a).get('b')

>
> Proxy went a different way for invoke, composing get and call. No idea
how that would compose for promises at this early stage.
>
> —
> Reply to this email directly or view it on GitHub.

-- 
  Cheers,
  MarkM

**Comment by egasimus** [comment]
So `Q(..., ...)` is a shorthand for `Q.all(..., ...)`? Cool, I didn't know that.

The `!` syntax is an interesting proposal for sure, but -- my distaste for reducing compactness while gaining little in the way of expressiveness by hacking new primitives into JS aside -- I can't really fathom how you intend to implement it. Preprocessing? Some upcoming operator overloading feature that I'm not aware of yet?

>Proxy

As in [this one](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)? Or some namesake lib?
